Organization, variable checks, error reporting
Added headers to major sections
Cleaned up variable checks
Added check for manifest_template.conf file
Added checks for mirabait and mira errors

diff --git a/jorg b/jorg
--- a/jorg
+++ b/jorg
@@ -1,4 +1,16 @@
 #!/usr/bin/env bash
+################################################################################
+#
+# GNU General Public License v3.0
+# Code written by Lauren Lui, Torben Nielsen, and Sean Jungbluth
+# https://github.com/lmlui/Jorg/
+#
+# Contact Lauren Lui with questions (lmlui@lbl.gov)
+#
+# Jorg is a script that uses the assembler MIRA to help circularize 
+#   metagenome-assembled genomes, but can also be used to improve bins
+#
+################################################################################
 
 # Commands returning a non-zero exit code will cause an immediate exit
 set -e
@@ -6,7 +18,9 @@ set -e
 # Software version, starting at 1.0.0
 jorg_version=1.0.0
 
+################################################################################
 # Menu banner
+################################################################################
 function ascii_text_banner() {
     echo "        _                               __    __    __    __              "
     echo "       | | ___  _ __ __ _              /  \  /  \  /  \  /  \             "
@@ -16,14 +30,17 @@ function ascii_text_banner() {
     echo "                    |___/        |/   \_/   \_/   \_/   \    o \          "
     echo "                                                         \_____/--<       "
 }
-
+################################################################################
 # Version reporting
+################################################################################
 function display_version() {
     echo "$jorg_version"
     exit 1
 }
 
+################################################################################
 # Help menu
+################################################################################
 function display_help() {
     echo "--------------------------------------------------------------------------"
     ascii_text_banner
@@ -35,9 +52,9 @@ function display_help() {
     echo "Authors: Lauren Lui (lmlui@lbl.gov), Torben Nielsen, Adam Arkin"
     echo "--------------------------------------------------------------------------"
     echo " "
-    echo "Usage: jorg -b bin.186.fa -r SRX3307784_clean.fastq.gz -k 33 -c 50 -i 5 --high_contig_num no"
+    echo "Usage: jorg -b bin.1.fa -r interleaved_reads.fastq.gz -k 33 -c 50 -i 5 --high_contig_num no"
     echo "or"
-    echo "Usage: jorg -b bin.186.fa --forward SRX3307784_1.fastq.gz --reverse SRX3307784_2.fastq.gz -k 33 -c 50 -i 5 --high_contig_num no"
+    echo "Usage: jorg -b bin.1.fa --forward reads_1.fastq.gz --reverse reads_2.fastq.gz -k 33 -c 50 -i 5 --high_contig_num no"
     echo
     echo "   -b, --bin_fasta_file       Genome bin in fasta format."
     echo "   -r, --reads_file           Interleaved metagenome reads file in fastq or fastq.gz format."
@@ -50,9 +67,9 @@ function display_help() {
     echo "   -v, --version              Print version number and exit."
     echo "   -h, --help                 Show this message."
     echo " "
-    echo "Extended Usage: jorg --bin_fasta_file bin.186.fa --reads_file SRX3307784_clean.fastq.gz --kmer_length 33 --min_coverage 50 --iterations 5 --high_contig_num no "
+    echo "Extended Usage: jorg --bin_fasta_file bin.1.fa --reads_file interleaved_reads.fastq.gz --kmer_length 33 --min_coverage 50 --iterations 5 --high_contig_num no "
     echo "or"
-    echo "jorg --bin_fasta_file bin.186.fa --forward SRX3307784_1.fastq.gz --reverse SRX3307784_2.fastq.gz --kmer_length 33 --min_coverage 50 --iterations 5 --high_contig_num no "
+    echo "jorg --bin_fasta_file bin.1.fa --forward reads_1.fastq.gz --reverse reads_2.fastq.gz --kmer_length 33 --min_coverage 50 --iterations 5 --high_contig_num no "
     echo " "
     echo "Please cite: Lui LM, Nielsen TN, Arkin AP. 2020, biorxiv (https://www.biorxiv.org/content/10.1101/2020.03.05.979740v2.full)."
     exit 1
@@ -61,10 +78,26 @@ function display_help() {
 # If jorg entered with no other input then will display help menu
 [ $# -eq 0 ] && { display_help ; exit 1; }
 
-# Jorg variable declarations
+################################################################################
+# Check for dependencies
+################################################################################
+
+# Check for MIRA installation
+command -v mira >/dev/null 2>&1 || { echo >&2 "Error: unable to locate MIRA. Please make sure MIRA is installed on your system. Exiting."; exit 1; }
+
+# Check for Seqtk installation
+command -v seqtk >/dev/null 2>&1 || { echo >&2 "Error: unable to locate Seqtk. Please make sure Seqtk is installed on your system. Exiting."; exit 1; }
+
+# Capture seqtk stout, but this doesn't work, it causes a hang
+#seqtk 2> /tmp/seqtk_version.tmp
+
+################################################################################
+# Variable Declarations
+################################################################################
+
 bin_fasta_file="NULL"
 reads_file="NULL"
-reads_foward="NULL"
+reads_forward="NULL"
 reads_reverse="NULL"
 kmer_length=33
 min_coverage=50 # originally 200, may need to fix. 50 required to prevent filtering all contigs after iteration #1
@@ -111,37 +144,52 @@ while [ "$1" != "" ]; do
     shift
 done
 
+################################################################################ 
+# Variable Checks
+################################################################################ 
+
 # Convert relevant abnormal entrees for high_contig_num variable
 if [ ! "$high_contig_num" == "n" ] || [ ! "$high_contig_num" == "N" ] || [ ! "$high_contig_num" == "No" ]; then
     high_contig_num="no"
 fi
 
 # Check for existence of input fasta file
-if [[ ! "$bin_fasta_file" = *[!\ ]* ]]; then
+if [ "$bin_fasta_file" = "NULL" ]; then
     echo "Input bin fasta file not defined (set using -b, --bin_fasta_file). Exiting."
     exit 1
 fi
 
 # Check for existence of input fastq reads file
-if [[ ! "$reads_file" = *[!\ ]* ]] || [[ ! "$reads_forward" = *[!\ ]* ]] || [[ ! "$reads_reverse" = *[!\ ]* ]] ; then
-    echo "Input reads fastq file not defined (set using -r, --reads_file or --foward and --reverse for paired end reads). Exiting."
-    exit 1
+if [ "$reads_file" = "NULL" ]
+then
+	if [ "$reads_forward" = "NULL" ] && [ "$reads_reverse" = "NULL" ] 
+	then
+		echo "Input reads fastq file not defined (set using -r, --reads_file or --foward and --reverse for paired end reads). Exiting."
+    		exit 1
+	elif [ "$reads_forward" = "NULL" ]
+        then
+                echo "Are you missing the forward reads file? Input reads fastq file not defined (set using -r, --reads_file or --foward and --reverse for paired end reads). Exiting."
+                exit 1
+	elif [ "$reads_reverse" = "NULL" ]
+	then
+		echo "Are you missing the reverse reads file? Input reads fastq file not defined (set using -r, --reads_file or --foward and --reverse for paired end reads). Exiting."
+                exit 1 
+	fi
 fi
+
+#Check for manifest template file
+if [ ! -e "manifest_template.conf" ] 
+then 
+	echo "Missing manifest_template.conf file.  Copy it into current directory."
+	exit 1
+fi
+
+################################################################################
+# Log File
+################################################################################
 
 # Name jorg logfile based on input bin and date/time
 jorg_logfile="Jorg_${bin_fasta_file}_$(date +%c | sed 's/[: ]/-/g').log"
-
-# Check for MIRA installation
-command -v mira >/dev/null 2>&1 || { echo >&2 "Error: unable to locate MIRA. Please make sure MIRA is installed on your system. Exiting."; exit 1; }
-
-# Check for MIRABAIT installation
-command -v mirabait >/dev/null 2>&1 || { echo >&2 "Error: unable to locate MIRABAIT. Please make sure MIRABAIT is installed on your system. Exiting."; exit 1; }
-
-# Check for Seqtk installation
-command -v seqtk >/dev/null 2>&1 || { echo >&2 "Error: unable to locate Seqtk. Please make sure Seqtk is installed on your system. Exiting."; exit 1; }
-
-# Capture seqtk stout, but this doesn't work, it causes a hang
-#seqtk 2> /tmp/seqtk_version.tmp
 
 # Start logging and timer
 jorg_time_start=$(date +%s)
@@ -169,7 +217,7 @@ if [ ! -f "$reads_file" ]
 then
     if  [ ! -f "$reads_forward" ] || [ ! -f "$reads_reverse" ]
     then
-        echo "contig file not found: reads file(s)" | tee -a "$jorg_logfile"
+        echo "File not found: reads file(s)" | tee -a "$jorg_logfile"
         echo "Exiting." | tee -a "$jorg_logfile"
         exit 1
     fi
@@ -183,12 +231,12 @@ if [[ $(grep -c "^>" "$bin_fasta_file") -gt 2500 ]] && [[ ! "$high_contig_num" =
     exit 1
 fi
 
-# Jorg variable declarations
+
 # Get the bin ID by removing the file extension
 # fafilepath="bin.186.fa"
 # fqfilepath="SRX3307784_clean.fastq.gz"
 fafilepath=${bin_fasta_file}
-#This is only a temporary fix; mirabait allows for paired end reads but we have to work out the 
+#This is only a temporary fix 
 if [ "$reads_file" == "NULL" ] 
 then  
         fqfilepath=${reads_forward}   #probably should be finessed a little more  
@@ -206,14 +254,16 @@ if [ $binID = $fqbinID ]; then
     exit 1
 fi
 
-# Copy original file to avoid rewriting over it
-outfile="$binID".out.fasta
+################################################################################
+# Run Jorg
+################################################################################
 
 # Jorg running and logging
 echo " " | tee -a "$jorg_logfile"
 echo "***Start running Jorg***" | tee -a "$jorg_logfile"
 
-# Copy input fasta file to avoid overwriting
+# Copy original file to avoid rewriting over it 
+outfile="$binID".out.fasta 
 cp "$bin_fasta_file" "$outfile"
 
 # Make manifest file for MIRA
@@ -231,7 +281,6 @@ echo "Start: generating new directory named 'Iterations'" | tee -a "$jorg_logfil
 mkdir -p Iterations
 echo "End: generating new directory named 'Iterations'" | tee -a "$jorg_logfile"
 
-
 for (( i = 1; i <= "$iterations"; i++ )); do
     echo " " | tee -a "$jorg_logfile"
     echo "*Start: Jorg iteration # ${i}*" | tee -a "$jorg_logfile"
@@ -241,7 +290,8 @@ for (( i = 1; i <= "$iterations"; i++ )); do
     # Recruit reads with mirabait
     mirabait_time_start=$(date +%s)
     echo "Start: recruiting reads with mirabait" | tee -a "$jorg_logfile"
-    # mirabait -k 33 -b "$outfile" -P SRX3307784_clean.fastq -o "$binID".fastq &> mirabait.log
+    
+    # Example of using mirabait: mirabait -k 33 -b "$outfile" -P SRX3307784_clean.fastq -o "$binID".fastq &> mirabait.log
     
     if [ "$reads_file" == "NULL" ] 
     then  
@@ -249,9 +299,22 @@ for (( i = 1; i <= "$iterations"; i++ )); do
     else
             mirabait -k "$kmer_length" -b "$outfile" -P "$reads_file" -o "$binID".fastq &> mirabait_iteration_${i}.log
     fi
-    
+  
     mirabait_time_elapsed=$(( $(date +%s) - $mirabait_time_start ))
     echo "End: recruiting reads with mirabait" - $mirabait_time_elapsed" seconds elapsed." | tee -a "$jorg_logfile"
+
+    #Check if mirabait finished properly
+    if [ $(tail mirabait_iteration_${i}.log | grep -c "Thank you for noticing that this is *NOT* a crash") == 1 ] 
+    then 
+            echo "mirabait had a controlled stop. Check mirabait_iteration_${i}.log for errors." | tee -a "$jorg_logfile" 
+    	    exit 1
+    fi 
+    if [ $(tail  mirabait_iteration_${i}.log | grep -c "Baiting process finished.") == 0 ]; then 
+	    echo "mirabait may have had errors. Check mirabait.log." | tee -a "$jorg_logfile" 
+    else
+	    echo "Recruiting reads with mirabait appears to have finished successfully." | tee -a "$jorg_logfile"
+    fi
+	
 
     # Check if the reads file is empty.  Seqtk will hang if the input file is empty.
     echo "Start: check if fastq file empty." | tee -a "$jorg_logfile"
@@ -278,12 +341,31 @@ for (( i = 1; i <= "$iterations"; i++ )); do
     mira_assembly_time_elapsed=$(( $(date +%s) - $mira_assembly_time_start ))
     echo "End: run MIRA assembly" - $mira_assembly_time_elapsed" seconds elapsed." | tee -a "$jorg_logfile"
 
+    #### Check mira log file for status
+    # MIRA finished
+    if [ $(tail mira_iteration_${i}.log | grep -c "We're done here, thank you for using MIRA.") == 1 ]
+    then
+            echo "MIRA assembly finished. " | tee -a "$jorg_logfile"
+    fi
+    # MIRA finished but could not get long contigs
+    if [ $(tail mira_iteration_${i}.log | grep -c "Large contigs could not be extracted, sorry.") == 1 ] 
+    then 
+            echo "Large contigs could not be extracted from the MIRA assembly. Although the MIRA assembly finished no more iterations are possible. Check mira_iteration_${i}.log" | tee -a "$jorg_logfile" 
+    	    exit 1
+    fi 
+    # MIRA had an error
+    if [ $(tail mira_iteration_${i}.log | grep -c "Thank you for noticing that this is *NOT* a crash") == 1 ]
+    then
+            echo "MIRA had a controlled stop. Check mira_iteration_${i}.log for errors." | tee -a "$jorg_logfile"
+    fi
+
     # Get MIRA assembly file
     echo "Start: get MIRA assembly file" | tee -a "$jorg_logfile"
     cp "$binID"_assembly/"$binID"_d_results/"$binID"_out.unpadded.fasta "$binID"_MIRA.fasta
     echo "End: get MIRA assembly file" | tee -a "$jorg_logfile"
 
     # Get contigs that are greater than 1000bp and have coverage greater than the indicated minimum
+    # Should add an option for controlling the minimum contig size 
     echo "Start: get contigs >1000bp and with sufficient coverage" | tee -a "$jorg_logfile"
     awk -v coverage_min="$min_coverage" '{if($2 >= 1000 && $6 >= coverage_min || NR == 1) print}' "$binID"_assembly/"$binID"_d_info/"$binID"_info_contigstats.txt > list.txt
     echo "End: get contigs >1000bp and with sufficient coverage" | tee -a "$jorg_logfile"
